services:
  node-red:
    image: nodered/node-red:4.1.2-22-minimal
    restart: unless-stopped
    environment:
      TZ: Europe/Warsaw
    volumes:
      - ./node-red/data:/data
      - ./node-red/settings.js:/data/settings.js:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - edge
  nginx:
    image: nginx:1.29-alpine-slim
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-8091}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/502.html:/usr/share/nginx/html/502.html:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - edge

networks:
  edge:
