/**
 * Utility functions for processing configuration data.
 * Includes filtering, normalization, and comparison helpers.
 */

/**
 * Filter out auto-generated fields from configuration data.
 * Removes fields like kind, mcp_id, pca_id, pcf_id, pin that are auto-generated
 * based on boneio_output or boneio_input.
 */
export function filterAutoGeneratedFields(data: any): any {
  if (!data || typeof data !== 'object') return data;
  
  // Create a deep copy to avoid mutating original
  const filtered = JSON.parse(JSON.stringify(data));
  
  // Filter outputs - remove auto-generated fields if boneio_output exists
  if (Array.isArray(filtered)) {
    return filtered.map((item: any) => {
      if (item && typeof item === 'object') {
        // If boneio_output exists, remove auto-generated fields
        if (item.boneio_output) {
          const { kind, mcp_id, pca_id, pcf_id, pin, ...rest } = item;
          return rest;
        }
        // If boneio_input exists, remove auto-generated fields
        if (item.boneio_input) {
          const { kind, pin, gpiochip, line, ...rest } = item;
          return rest;
        }
      }
      return item;
    });
  }
  
  // Handle object with output/input arrays
  if (filtered.output && Array.isArray(filtered.output)) {
    filtered.output = filtered.output.map((output: any) => {
      if (output.boneio_output) {
        const { kind, mcp_id, pca_id, pcf_id, pin, ...rest } = output;
        return rest;
      }
      return output;
    });
  }
  
  if (filtered.input && Array.isArray(filtered.input)) {
    filtered.input = filtered.input.map((input: any) => {
      if (input.boneio_input) {
        const { kind, mcp_id, pca_id, pcf_id, pin, ...rest } = input;
        return rest;
      }
      return input;
    });
  }
  
  // Remove empty/null values to clean up the YAML
  return removeEmptyValues(filtered);
}

/**
 * Remove empty/null/undefined values from an object recursively.
 */
export function removeEmptyValues(obj: any): any {
  if (Array.isArray(obj)) {
    return obj.map(removeEmptyValues).filter(item => item !== null && item !== undefined);
  } else if (obj !== null && typeof obj === 'object') {
    const cleaned: any = {};
    for (const [key, value] of Object.entries(obj)) {
      const cleanedValue = removeEmptyValues(value);
      // Keep the key if value is not null/undefined/empty string/empty array/empty object
      if (cleanedValue !== null && 
          cleanedValue !== undefined && 
          cleanedValue !== '' &&
          !(Array.isArray(cleanedValue) && cleanedValue.length === 0) &&
          !(typeof cleanedValue === 'object' && Object.keys(cleanedValue).length === 0)) {
        cleaned[key] = cleanedValue;
      }
    }
    return cleaned;
  }
  return obj;
}

/**
 * Normalize data for comparison - remove empty objects/arrays/nulls.
 */
export function normalizeForComparison(obj: any): any {
  if (obj === null || obj === undefined) return undefined;
  if (Array.isArray(obj)) {
    const filtered = obj.map(normalizeForComparison).filter(v => v !== undefined);
    return filtered.length > 0 ? filtered : undefined;
  }
  if (typeof obj === 'object') {
    const result: any = {};
    for (const [key, value] of Object.entries(obj)) {
      const normalized = normalizeForComparison(value);
      if (normalized !== undefined) {
        result[key] = normalized;
      }
    }
    return Object.keys(result).length > 0 ? result : undefined;
  }
  if (obj === '') return undefined;
  return obj;
}

/**
 * Deep comparison using sorted JSON stringify.
 */
export function sortedStringify(obj: any): string {
  if (obj === null || obj === undefined) return 'null';
  if (Array.isArray(obj)) {
    return '[' + obj.map(sortedStringify).join(',') + ']';
  }
  if (typeof obj === 'object') {
    const keys = Object.keys(obj).sort();
    return '{' + keys.map(k => JSON.stringify(k) + ':' + sortedStringify(obj[k])).join(',') + '}';
  }
  return JSON.stringify(obj);
}

/**
 * Check if two data objects are equal after normalization.
 */
export function isDataEqual(data1: any, data2: any): boolean {
  const normalized1 = normalizeForComparison(data1);
  const normalized2 = normalizeForComparison(data2);
  return sortedStringify(normalized1) === sortedStringify(normalized2);
}
