/**
 * YAML conversion utilities for configuration data.
 */
import * as yaml from 'js-yaml';
import { stripHiddenAndDefaults, convertMillisecondsToTimeperiod } from './configSchemaUtils';
import { filterAutoGeneratedFields } from './configDataUtils';

interface SectionInfo {
  name: string;
  schema: any;
  normalizedSchema: any;
  uiSchema: any;
}

/**
 * Convert timeperiod fields from milliseconds (number) back to string with unit.
 * This is needed because formData stores timeperiods as numbers for form inputs.
 */
function convertTimeperiodsForYaml(obj: any, schema: any): any {
  if (!obj || typeof obj !== 'object') return obj;
  
  if (Array.isArray(obj)) {
    const itemsSchema = schema?.items;
    return obj.map((item: any) => convertTimeperiodsForYaml(item, itemsSchema));
  }
  
  const result = { ...obj };
  const properties = schema?.properties || {};
  
  Object.keys(result).forEach(key => {
    const propSchema = properties[key];
    const value = result[key];
    
    // Check if this is a timeperiod field
    if (propSchema && propSchema['x-timeperiod'] === true && typeof value === 'number') {
      result[key] = convertMillisecondsToTimeperiod(value);
    }
    // Recursively handle nested objects/arrays
    else if (typeof value === 'object' && value !== null) {
      result[key] = convertTimeperiodsForYaml(value, propSchema);
    }
  });
  
  return result;
}

/**
 * Convert MCP23017 addresses to hex format.
 */
function convertMcp23017Addresses(data: any[]): any[] {
  return data.map((entry: any) => {
    if (entry && entry.address !== undefined) {
      let addr = entry.address;
      // Convert number to hex string
      if (typeof addr === 'number') {
        addr = `0x${addr.toString(16)}`;
      } else if (typeof addr === 'string' && !addr.startsWith('0x')) {
        const num = parseInt(addr, 10);
        if (!isNaN(num)) {
          addr = `0x${num.toString(16)}`;
        }
      }
      return { ...entry, address: addr };
    }
    return entry;
  });
}

/**
 * Convert data to YAML format (with defaults stripped).
 */
export function convertToYaml(
  data: any, 
  sectionName: string | undefined, 
  sections: SectionInfo[]
): string {
  try {
    // Filter out auto-generated fields
    let filteredData = filterAutoGeneratedFields(data);
    
    // Strip default values if we have schema for this section
    if (sectionName) {
      const sectionInfo = sections.find(s => s.name === sectionName);
      if (sectionInfo) {
        filteredData = stripHiddenAndDefaults(
          filteredData,
          sectionInfo.normalizedSchema,
          sectionInfo.uiSchema || {}
        );
      }
    }
    
    // Special handling for mcp23017 - convert addresses to hex format
    if (sectionName === 'mcp23017' && Array.isArray(filteredData)) {
      filteredData = convertMcp23017Addresses(filteredData);
    }
    
    // Apply timeperiod conversion if we have schema
    if (sectionName) {
      const sectionInfo = sections.find(s => s.name === sectionName);
      if (sectionInfo?.schema) {
        filteredData = convertTimeperiodsForYaml(filteredData, sectionInfo.schema);
      }
    }
    
    // Convert to YAML format
    const yamlString = yaml.dump(filteredData, {
      indent: 2,
      lineWidth: -1, // No line wrapping
      noRefs: true,
      quotingType: '"',
      forceQuotes: false,
      sortKeys: false,
      flowLevel: -1, // Use block style (lists with -) instead of flow style
      styles: {
        '!!null': 'empty', // Represent null as empty
      },
    });
    
    return yamlString;
  } catch (error) {
    console.error('Error converting to YAML:', error);
    // Fallback to JSON if YAML conversion fails
    return JSON.stringify(data, null, 2);
  }
}
