#!/usr/bin/env python3
"""Generate MANIFEST.sha256 for boneio migration assets.

Run from the project root:
    python scripts/generate_manifest.py

The generated file is written to:
    boneio/migrations/assets/MANIFEST.sha256

Format (one line per asset):
    <sha256hex>  <relative-path-from-assets-dir>
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path


ASSETS_DIR = Path(__file__).parent.parent / "boneio" / "migrations" / "assets"
MANIFEST_PATH = ASSETS_DIR / "MANIFEST.sha256"

# Files to skip in the manifest
SKIP_FILES = {"MANIFEST.sha256"}


def sha256_file(path: Path) -> str:
    """Return SHA-256 hex digest of file at path.

    Args:
        path: Path to the file.

    Returns:
        Lower-case hex SHA-256 string.
    """
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def generate_manifest() -> int:
    """Scan assets directory and write MANIFEST.sha256.

    Returns:
        0 on success, 1 on error.
    """
    if not ASSETS_DIR.is_dir():
        print(f"ERROR: Assets directory not found: {ASSETS_DIR}", file=sys.stderr)
        return 1

    entries: list[tuple[str, str]] = []

    for asset_path in sorted(ASSETS_DIR.rglob("*")):
        if not asset_path.is_file():
            continue
        if asset_path.name in SKIP_FILES:
            continue

        rel = asset_path.relative_to(ASSETS_DIR)
        sha = sha256_file(asset_path)
        entries.append((sha, str(rel)))

    lines = [
        "# BoneIO migration asset manifest",
        "# Format: <sha256>  <relative-path>",
        "# Generated by scripts/generate_manifest.py — do not edit manually",
        "",
    ]
    for sha, rel in sorted(entries, key=lambda e: e[1]):
        lines.append(f"{sha}  {rel}")
    lines.append("")

    MANIFEST_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Written {len(entries)} entries to {MANIFEST_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(generate_manifest())
